In [1]:
int restult = 0;

SyntaxError: invalid syntax (Temp/ipykernel_10428/3822676306.py, line 1)

In [3]:
result = 0;
for i in range(100):
    result += i

In [4]:
x = 4
x = "four"

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [12]:
L2 = [str(c) for c in L]
L

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [14]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [18]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [20]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [27]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.random.random((3,3))

array([[0.01749092, 0.6902633 , 0.23778347],
       [0.364474  , 0.61957315, 0.18080714],
       [0.03047413, 0.73399448, 0.00408466]])

In [30]:
np.random.normal(0,1,(3,3))

array([[-1.25263484, -0.08530626,  0.64974017],
       [-2.19103184, -0.57931363, -0.25562248],
       [ 1.52599997, -1.2111444 ,  1.34660048]])

In [32]:
np.random.randint(0,10,(3,3))

array([[2, 7, 8],
       [8, 0, 5],
       [1, 6, 4]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.empty(3)

array([1., 1., 1.])

In [37]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [38]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [41]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [43]:
print("x3 ndim",x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [44]:
print("dtype:",x3.dtype)

dtpe: int32


In [45]:
print("itemsize:",x3.itemsize,"bytes")

itemsize: 4 bytes


In [46]:
x2[0][0]

3

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x[:5]

array([0, 1, 2, 3, 4])

In [50]:
x[5:]

array([5, 6, 7, 8, 9])

In [51]:
x[4:7]

array([4, 5, 6])

In [52]:
x[::2]

array([0, 2, 4, 6, 8])

In [53]:
x[1::2]

array([1, 3, 5, 7, 9])

In [54]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [55]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [57]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [58]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [59]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [60]:
print(x2[:,0])

[3 7 1]


In [61]:
print(x2[0,:])

[3 5 2 4]


In [62]:
print(x2[0])

[3 5 2 4]


In [65]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [66]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [67]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [68]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [70]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [71]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [73]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [75]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [76]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [77]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [78]:
x = np.array([1,2,3])

In [79]:
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [84]:
z = [99,99,99]
z2 = np.concatenate([x,y,z])

In [85]:
grid = np.array([[1,2,3],[4,5,6]])

In [86]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [94]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [99]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [100]:
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [105]:
x = [1,23,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[ 1 23 99] [99  3] [2 1]


In [107]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [111]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
