In [1]:
from sklearn import datasets

"""
irisデータセットの内容
data:特徴量
feature_names：各カラムの特徴名が格納されている
target:分類に使うラベル
target_names: ラベル名一覧

digitsデータセット
数字の画像データと対応するラベルのデータセット

data:特徴量
target: 画像に対応する種類

"""


iris = datasets.load_iris()
digits = datasets.load_digits()

In [3]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [4]:
digits.target #ラベル

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
from sklearn import svm 
clf = svm.SVC(gamma=0.001,C=100.)

In [6]:
#　訓練データ一式、訓練データのラベル一式
#　画像が数字のなにか予測するモデルを学習
clf.fit(digits.data[:-1],digits.target[:-1])

SVC(C=100.0, gamma=0.001)

In [8]:
print(digits.data[-1:])
print(digits.target[-1:])
clf.predict(digits.data[-1:]) #訓練データの末尾一つを入力して予測をする

[[ 0.  0. 10. 14.  8.  1.  0.  0.  0.  2. 16. 14.  6.  1.  0.  0.  0.  0.
  15. 15.  8. 15.  0.  0.  0.  0.  5. 16. 16. 10.  0.  0.  0.  0. 12. 15.
  15. 12.  0.  0.  0.  4. 16.  6.  4. 16.  6.  0.  0.  8. 16. 10.  8. 16.
   8.  0.  0.  1.  8. 12. 14. 12.  1.  0.]]
[8]


array([8])

In [12]:
import numpy as np
from sklearn import random_projection

rng = np.random.RandomState(0)
X = rng.rand(10,2000)
X = np.array(X,dtype='float32')
print(X.shape)

## 任意の行列をランダムな行列と演算して、次元削減
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
X_new.shape

(10, 2000)


(10, 1973)

In [17]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC

X,y = load_iris(return_X_y = True)

clf = SVC()
clf.set_params(kernel='linear').fit(X,y)
clf.predict(X[:5])

clf.set_params(kernel='rbf').fit(X,y)
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

In [21]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]

classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X,y).predict(X)

array([0, 0, 1, 1, 2])

In [22]:
y = LabelBinarizer().fit_transform(y)
print(y)
classif.fit(X,y).predict(X)

[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]]


array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
from sklearn.preprocessing import MultiLabelBinarizer

y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])