In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [3]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
from sklearn import svm 
clf = svm.SVC(gamma=0.001,C=100.)

In [7]:
clf.fit(digits.data[:-1],digits.target[:-1])

SVC(C=100.0, gamma=0.001)

In [8]:
clf.predict(digits.data[-1:])

array([8])

In [12]:
import numpy as np
from sklearn import random_projection

rng = np.random.RandomState(0)
X = rng.rand(10,2000)
X = np.array(X,dtype='float32')
print(X.shape)

transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
X_new.shape

(10, 2000)


(10, 1973)

In [17]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.svm import SVC

X,y = load_iris(return_X_y = True)

clf = SVC()
clf.set_params(kernel='linear').fit(X,y)
clf.predict(X[:5])

clf.set_params(kernel='rbf').fit(X,y)
clf.predict(X[:5])

array([0, 0, 0, 0, 0])

In [21]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer

X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]

classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X,y).predict(X)

array([0, 0, 1, 1, 2])